# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632d6996241e89107088c435bff741d685330d02f1cd39a2233824b5e5c215e80efe6ee04e3e0c767bd8c467847ced0f62b3d83bee0f95ef7ab8d37084a05a2c

test:
  secret_key_base: 07b89c7de9694966eca14558b1879562be4379d154bce44eb3d7110cb41c2c2dddf2d1fb9ad7b6f3ef2df2b758ea8f64df5938baaa6ab793903c42d5fc3f2d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
